// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HubitatVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HubitatVSString = "0899a45c-32a0-48cb-8627-4af2e2976fc3";
        public static Guid HubitatVS = new Guid(HubitatVSString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);

        public const string IconsString = "3b6d4b18-2382-4761-b792-00ea3526509b";
        public static Guid Icons = new Guid(IconsString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int HubitatMenuGroup = 0x0001;
        public const int HubitatWorkspaceContextMenuGroup = 0x0002;
        public const int ShowHubitatConnectionsToolWindowCommand = 0x0102;
        public const int PublishToHubitatCommand = 0x0103;
        public const int HubitatContextMenuFlyout = 0x0104;
        public const int HubitatContextMenuFlyoutGroup = 0x0105;
        public const int CompareWithHubCommand = 0x0106;
        public const int HubitatAdornmentContextMenu = 0x0107;
        public const int HubitatAdornmentContextMenuGroup = 0x0108;
        public const int TogglePublishOnSaveCommand = 0x0109;
        public const int ReplaceWithHubVersionCommand = 0x010A;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int Logo = 0x0001;
    }
}
